# Generated by Django 4.2.5 on 2023-11-06 12:41

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='level',
            field=models.CharField(max_length=10, null=True, verbose_name=quiz.models.QuesModel),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2')], default='level1', max_length=10),
        ),
    ]
