# Generated by Django 4.2.5 on 2023-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_resultmodel_level_alter_quesmodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
