# Generated by Django 4.2.5 on 2023-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_resultmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
