# Generated by Django 4.2.5 on 2023-11-15 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_resultmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
